### ISSUE TITLE
Panic when blevesearch isEncodedSingle

### ISSUE THREAD

**Issue by fatpo** [blevesearch/vellum#21]
issue:
```
Unfortunately, we are unable to locate the input parameters of the function, and we do not know how this panic occurred. In fact, its appearance is very occasional, only occasionally appearing once every two or three weeks.

This may cause trouble in locating the issue for you.
```

version:
```
github.com/blevesearch/bleve/v2 v2.3.9
```

panic code:
```
func (f *fstStateV1) isEncodedSingle() bool {
	if f.data[f.top]>>7 > 0 {
		return true
	}
	return false
}
```

panic error traceback:
```
panic err goroutine 841285 [running]:
runtime/debug.Stack()
    /usr/local/go/src/runtime/debug/stack.go:24 +0x65
git.wakaka.com/wakaka/wkksearch/search/search-downgrade/pipline/search.(*Engine).MultiRecall.func1.1()
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/pipline/search/recall.go:30 +0x56
panic({0x25f0800, 0xc296b98a80})
    /usr/local/go/src/runtime/panic.go:884 +0x212
github.com/blevesearch/vellum.(*fstStateV1).isEncodedSingle(...)
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/vellum/decoder_v1.go:100
github.com/blevesearch/vellum.(*fstStateV1).TransitionFor(0xc39ae24048?, 0xcd?)
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/vellum/decoder_v1.go:239 +0x2d2
github.com/blevesearch/vellum.(*FST).get(0xc291e1a140, {0xc29332ec5a, 0x5, 0xc2960869a0?}, {0x2a767a8, 0xc291d470e8})
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/vellum/fst.go:78 +0xcf
github.com/blevesearch/vellum.(*Reader).Get(...)
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/vellum/fst.go:299
github.com/blevesearch/zapx/v15.(*Dictionary).postingsList(0xc29be7c3c0, {0xc29332ec5a?, 0x1?, 0xc000675980?}, 0xc330d6f070?, 0xc294908f00)
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/zapx/v15/dict.go:59 +0x88
github.com/blevesearch/zapx/v15.(*Dictionary).PostingsList(0xc330d6f000?, {0xc29332ec5a?, 0x3?, 0x202e9ba?}, 0x3f?, {0x2a76be0?, 0xc294908f00?})
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/zapx/v15/dict.go:48 +0x47
github.com/blevesearch/bleve/v2/index/scorch.(*IndexSnapshot).TermFieldReader(0xc330d6f000, {0x0?, 0x0}, {0xc29332ec5a, 0x5, 0xa6}, {0x270c178, 0x3}, 0x1, 0x1, ...)
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/bleve/v2/index/scorch/snapshot_index.go:572 +0x668
github.com/blevesearch/bleve/v2/index/scorch.(*IndexSnapshotTermFieldReader).Advance(0xc000cd6b60, {0xc2958caee0, 0x8, 0x8}, 0xc00104ce28)
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/bleve/v2/index/scorch/snapshot_index_tfr.go:149 +0xf6
github.com/blevesearch/bleve/v2/search/searcher.(*TermSearcher).Advance(0xc00104ce00, 0x8?, {0xc2958caee0?, 0x1?, 0xc292896570?})
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/bleve/v2/search/searcher/search_term.go:109 +0x153
github.com/blevesearch/bleve/v2/search/searcher.(*DisjunctionSliceSearcher).Advance(0xc291da85a0, 0xc2c89a7e60, {0xc2958caee0, 0x8, 0x8})
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/bleve/v2/search/searcher/search_disjunction_slice.go:241 +0x250
github.com/blevesearch/bleve/v2/search/searcher.(*FilteringSearcher).Advance(0xc291ccba58, 0x2a733a0?, {0xc2958caee0?, 0x8?, 0x8?})
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/bleve/v2/search/searcher/search_filter.go:69 +0x37
github.com/blevesearch/bleve/v2/search/searcher.(*DisjunctionSliceSearcher).Advance(0xc291db7400, 0xc2c89a7e60, {0xc2958caee0, 0x8, 0x8})
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/bleve/v2/search/searcher/search_disjunction_slice.go:241 +0x250
github.com/blevesearch/bleve/v2/search/searcher.(*ConjunctionSearcher).advanceChild(0xc291dbb880, 0xc2c89a7e60?, 0x0, {0xc2958caee0?, 0x8?, 0x8?})
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/bleve/v2/search/searcher/search_conjunction.go:253 +0xda
github.com/blevesearch/bleve/v2/search/searcher.(*ConjunctionSearcher).Next(0xc291dbb880, 0xc2c89a7e60)
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/bleve/v2/search/searcher/search_conjunction.go:190 +0x67e
github.com/blevesearch/bleve/v2/search/searcher.(*BooleanSearcher).advanceNextMust(0xc00075dad0, 0xc2c89a7e60, 0xc2958caa08?)
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/bleve/v2/search/searcher/search_boolean.go:165 +0x3c2
github.com/blevesearch/bleve/v2/search/searcher.(*BooleanSearcher).Next(0xc00075dad0, 0xc2c89a7e60)
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/bleve/v2/search/searcher/search_boolean.go:323 +0x458
github.com/blevesearch/bleve/v2/search/collector.(*TopNCollector).Collect(0xc2953361e0, {0x2a709f8, 0xc2c89a7830}, {0x2a7de20, 0xc00075dad0}, {0x2a81f08?, 0xc330d6f000?})
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/bleve/v2/search/collector/topn.go:206 +0x47f
github.com/blevesearch/bleve/v2.(*indexImpl).SearchInContext(0xc0002560e0, {0x2a70988, 0xc0000480f0}, 0xc0006f3380)
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/bleve/v2/index_impl.go:553 +0x870
github.com/blevesearch/bleve/v2.(*indexImpl).Search(0x0?, 0x0?)
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/vendor/github.com/blevesearch/bleve/v2/index_impl.go:369 +0x2a
git.wakaka.com/wakaka/wkksearch/search/search-downgrade/pipline/search/idx_manage.(*IdxManage).Search(...)
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/pipline/search/idx_manage/idx_manage.go:408
git.wakaka.com/wakaka/wkksearch/search/search-downgrade/pipline/search.(*Engine).MultiRecall.func1(0x202a88a?, 0xc29067e810)
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/pipline/search/recall.go:58 +0x19c
created by git.wakaka.com/wakaka/wkksearch/search/search-downgrade/pipline/search.(*Engine).MultiRecall
    /root/go/src/git.wakaka.com/wakaka/wkksearch/search/search-downgrade/pipline/search/recall.go:26 +0xb0
```

**Comment by abhinavdangeti** [comment]
Hey @Thejas-bhat would you look into this when you get a second will you?
